### ISSUE TITLE
Compiling `Ether: Transfer Ether to an account` sample fails due to missing BouncyCastle.Crypto dependency

### ISSUE THREAD

**Issue by iDawer** [Nethereum/Nethereum.Playground#52]
Hi, thank you for great work!

Compiling the sample at the playground fails with this output:

```
System.TypeLoadException: Could not load type of field 'Nethereum.Signer.EthECKey:SecureRandom' (0) due to: Could not load file or assembly 'BouncyCastle.Crypto, Version=1.8.2.0, Culture=neutral, PublicKeyToken=0e99375e54769942' or one of its dependencies.
   at Program.Main(String[] args)
   at Nethereum.Playground.Components.PlaygroundEditor.PlaygroundEditorViewModel.CompileAndRunCsharp()
   at Nethereum.Playground.Components.PlaygroundEditor.PlaygroundEditorViewModel.RunInternal()
```

That dependency is missing in `Remote Assemblies` and adding it manually does not help.

**Comment by juanfranblanco** [comment]
It might have not loaded properly, maybe it needs refreshing.
![image](https://github.com/Nethereum/Nethereum.Playground/assets/562371/39fdce4b-1c2f-4c1d-9f6e-4a3197ef9cb5)

![image](https://github.com/Nethereum/Nethereum.Playground/assets/562371/693625a0-91c6-4ec1-9152-efe725b6bc03)

**Comment by iDawer** [comment]
Ohh, that was connection issue. Loading through VPN works fine. Looks like my garbage ISP aren't doing good with their traffic regulation.

Sorry for bothering.
